/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\steve.glb
Author: Fatihpro64 (https://sketchfab.com/Fatihpro64)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-perfect-steve-rigged-1f098a7cc2744736ba13ab5bda7c74a8
Title: The-perfect-steve-rigged
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from 'react'
import { useFrame } from '@react-three/fiber'

export function Steve(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/glb/steve.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    console.log(actions)
    actions['Armature.001|Walk'].play();
  },[])
  useFrame(()=>{
    group.current.position.z+=0.02
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Steve_Riggedfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Sun" position={[-1185.21, -1055.96, 225.28]} rotation={[0, 1.49, 0.93]} scale={100}>
                  <group name="Object_5" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_6" />
                  </group>
                </group>
                <group name="Armature001" position={[-0.35, -204.18, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_8">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_26" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials['Scene_-_Root']} skeleton={nodes.Object_27.skeleton} />
                  </group>
                </group>
                <group name="Cube064_Cube000" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/glb/steve.glb')
