/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\walkRobot.glb
Author: AntijnvanderGun (https://sketchfab.com/AntijnvanderGun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-walk-animation-40e2de1d942f43eca60e2344c5e91d12
Title: Robot walk animation
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function WalkRobot(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/glb/walkRobot.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    actions['Take 001'].play()
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
          <group name="604b8ec4a03146bb9b38d4e0bdd31423fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="nurbsCircle1" position={[0, 0.91, -15.42]}>
                  <group name="nurbsCircle5" position={[0, 3.19, 3.17]} />
                </group>
                <group name="nurbsCircle3" position={[0, 0.62, 8.24]}>
                  <group name="nurbsCircle4" position={[0, -1.01, -0.46]} />
                </group>
                <group name="nurbsCircle6" position={[0.04, 33.95, 0.37]} rotation={[-0.23, 0.09, 0.03]} scale={19.89}>
                  <group name="nurbsCircle9" position={[0, 0.23, -0.13]} rotation={[0, 0.01, 0]}>
                    <group name="nurbsCircle7" position={[0.38, -0.35, -0.61]} rotation={[-1.7, -0.88, -0.22]} scale={0.26} />
                    <group name="nurbsCircle8" position={[-0.75, -0.53, 0.04]} rotation={[-1.63, 0.6, 0.11]} scale={0.26} />
                  </group>
                </group>
                <group name="Character1_Reference">
                  <group name="Object_114">
                    <primitive object={nodes._rootJoint} />
                  </group>
                </group>
                <group name="pCube51" position={[-13.01, 0, 0]}>
                  <mesh name="pCube51_lambert3_0" geometry={nodes.pCube51_lambert3_0.geometry} material={materials.lambert3} />
                </group>
                <group name="group">
                  <group name="pasted__pCube51" position={[-13.01, 0, 0]}>
                    <mesh name="pasted__pCube51_pasted__lambert3_0" geometry={nodes.pasted__pCube51_pasted__lambert3_0.geometry} material={materials.pasted__lambert3} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/glb/walkRobot.glb')
