/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\jumpingMan.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function JumpingMan(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/moonMan/jumpingMan.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="jumping" geometry={nodes.jumping.geometry} material={nodes.jumping.material} skeleton={nodes.jumping.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/moonMan/jumpingMan.glb')
