/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\swimmingMan.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'

export function SwimmingMan(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/moonMan/swimmingMan.glb')
  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="swimming" geometry={nodes.swimming.geometry} material={nodes.swimming.material} skeleton={nodes.swimming.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/moonMan/swimmingMan.glb')
